apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: {{ template "vernemq.fullname" . }}
  labels:
    app: {{ template "vernemq.name" . }}
    chart: {{ template "vernemq.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "vernemq.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "vernemq.name" . }}
        release: {{ .Release.Name }}
    spec:
      initContainers:
      - name: init-myservice
        image: busybox
        command: ['sh', '-c', 'until nslookup vernemq-master; do echo waiting for master; sleep 2; done;']

      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: DOCKER_VERNEMQ_ALLOW_ANONYMOUS
            value: "on"
          - name: DOCKER_VERNEMQ_DISCOVERY_NODE
            value: "vernemq-master.default.svc.cluster.local"
          ports:
            - containerPort: 1883
              name: mqtt
            - containerPort: 8888
              name: status
            - containerPort: 8080
              name: websock
            - containerPort: 44053
              name: epmd
            - containerPort: 4369
              name: data
            - containerPort: 9100
            - containerPort: 9101
            - containerPort: 9102
            - containerPort: 9103
            - containerPort: 9104
            - containerPort: 9105
            - containerPort: 9106
            - containerPort: 9107
            - containerPort: 9108
            - containerPort: 9109
          livenessProbe:
            httpGet:
              path: /status
              port: status
          readinessProbe:
            httpGet:
              path: /status
              port: status
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
